services:
  - type: web
    name: matrp-vk-bot
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: VK_TOKEN
        sync: false
      - key: VK_USER_ID
        sync: false
      - key: THREAD_URL
        sync: false
