name: MatRP → VK Notifier

on:
  schedule:
    - cron: '*/5 * * * *' # каждые 5 минут
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: node src/index.js
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_USER_ID: ${{ secrets.VK_USER_ID }}
          THREAD_URL: ${{ secrets.THREAD_URL }}
